RSTF_MODE_ARENA_init = {
	"Moving spawns..." call RSTF_fnc_dbg;

	// Move spawns to the center
	RSTF_SPAWNS set [SIDE_ENEMY, RSTF_POINT];
	RSTF_SPAWNS set [SIDE_FRIENDLY, RSTF_POINT];
	// TODO: Configurable?
	RSTF_RANDOM_SPAWN_WIDTH = RSTF_MODE_ARENA_RECTANGLE_SIZE;
	RSTF_RANDOM_SPAWN_HEIGHT = RSTF_MODE_ARENA_RECTANGLE_SIZE;
	RSTF_RANDOM_SPAWN_AVOID_ENEMIES = true;
	RSTF_RANDOM_SPAWN_AVOID_ENEMIES_RADIUS = RSTF_MODE_ARENA_RESPAWN_ENEMY_CHECK_RADIUS;

	// Some features have to be disabled
	RSTF_DISABLE_GROUP_SPAWNS = true;
	RSTF_DISABLE_SPAWN_TRANSPORTS = true;
	
	// TODO: Neutrals?
	// RSTF_SPAWNS set [SIDE_NEUTRAL, RSTF_POINT];
};

RSTF_MODE_ARENA_startLoop = RSTF_MODE_CLASSIC_startLoop;

RSTF_MODE_ARENA_scoreChanged = RSTF_MODE_CLASSIC_scoreChanged;
RSTF_MODE_ARENA_unitKilled = RSTF_MODE_CLASSIC_unitKilled;
RSTF_MODE_ARENA_taskCompleted = RSTF_MODE_CLASSIC_taskCompleted;
RSTF_MODE_ARENA_vehicleKilled = RSTF_MODE_CLASSIC_vehicleKilled;
